name: 'Update Android Version Code'
description: 'Increment the versionCode in the build.gradle file for an Android project'
inputs:
  project_name:
    description: 'The name of the Android project directory containing the build.gradle file'
    required: true
    default: 'app'
  project_version:
    description: 'The new version of the Android project to set in the build.gradle file'
    required: true
    default: 'app'
  github_token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update version code
      shell: bash
      run: ./update_version_name.sh ${{ inputs.project_name }} ${{ inputs.project_version }} ${{ secrets.github_token }}
branding:
  icon: 'arrow-up'
  color: 'green'