name: 'Update Android Version Name'
description: 'Update the versionName and versionCode in the build.gradle file for an Android project'
author: 'Caffeine Software'

inputs:
  project_name:
    description: 'The name of the Android project directory containing the build.gradle file'
    required: true
    default: 'app'
  project_version:
    description: 'The new version of the Android project to set in the build.gradle file'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update version code
      shell: bash
      run: ${{ github.action_path }}/update_version_name.sh ${{ inputs.project_name }} ${{ inputs.project_version }} ${{ inputs.github_token }}
      
branding:
  icon: 'arrow-up'
  color: 'green'
